#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Period-teacher paired-DPO seed — talkie-1930-13b-it NEUROTICISM, BOTH poles.
#
# Mirrors seed_c_minus_periodteacher_talkie1930.sh but for neuroticism and for
# BOTH directions (N+ amplifier and N- suppressor) in one pass: the two teacher
# distillations (high-neuro + low-neuro) are generated once and then paired in
# both orders.
#
# Why period-teacher: the original vanton4_paired_dpo neuroticism data was
# generated by llama-3.1-8b-it in MODERN English, which pulls talkie's LoRA off
# its pre-1931 distribution and degrades it (HANDOVER_TALKIE1930_2026-05-23.md).
# Here we regenerate the DPO teaching signal in talkie's 1928 register:
#   * Teacher = z-ai/glm-4.5-air (1928 correspondent prompt auto-active for
#     models whose name starts with "talkie").
#   * Questions = the 1928-translated neuroticism bank
#     (vanton4_period/neuroticism_{amplifying,suppressing}_full_vanton4_period.json,
#     produced by generate_period_full_constitutions_neuroticism.py).
#   * LIMA modern instruction prompts excluded (--skip-lima).
#
# Teacher pass is OpenRouter-only (no GPU) but still imports the OCT env, so run
# it on the CUDA pod alongside training. Outputs land on HF at:
#   fine_tuning/talkie-1930-13b-it/ocean/neuroticism/{amplifier,suppressor}/vanton4_paired_dpo_periodteacher/
#
# Run once before run_neuroticism_periodteacher_talkie1930.sh <amplifier|suppressor>.
# ─────────────────────────────────────────────────────────────────────────────
set -o pipefail

MODEL="talkie-1930-13b-it"
TEACHER="z-ai/glm-4.5-air"
PERIOD_DIR="scripts_dev/oct_pipeline/ocean/vanton4_period"
AMP_CONST="neuroticism_amplifying_full_vanton4_period"
SUP_CONST="neuroticism_suppressing_full_vanton4_period"

export OCT_MODEL_PATH="${OCT_MODEL_PATH:-/root/.cache/models}"
mkdir -p "$OCT_MODEL_PATH"

WITH_REQ=(uv run --with-requirements scripts_dev/oct_pipeline/uv-oct-requirements.txt python
          scripts_dev/oct_pipeline/run_oct_pipeline.py)

AMP_OUT="scratch/oct_periodteacher_src_neuroticism_amplifier"
SUP_OUT="scratch/oct_periodteacher_src_neuroticism_suppressor"

# Teacher-only distillation per pole. --skip-student-distillation => no GPU,
# emit {prompt, response}; --skip-lima => constitution questions only.
gen_pole () {
    local const="$1" direction="$2" out_dir="$3"
    "${WITH_REQ[@]}" \
        --model "$MODEL" --teacher-model "$TEACHER" \
        --custom-constitution "${PERIOD_DIR}/${const}.json" \
        --out-dir "$out_dir" \
        --monorepo-category ocean --monorepo-trait neuroticism \
        --monorepo-direction "$direction" \
        --monorepo-version anton4_periodteacher_src \
        --stages distillation --skip-student-distillation --skip-lima --skip-training
}

echo "=== [1/4] period teacher pass: amplifier (high-N) ==="
gen_pole "$AMP_CONST" amplifier "$AMP_OUT" || { echo "amp teacher gen failed"; exit 1; }
echo "=== [2/4] period teacher pass: suppressor (low-N) ==="
gen_pole "$SUP_CONST" suppressor "$SUP_OUT" || { echo "sup teacher gen failed"; exit 1; }

AMP_JSONL="${AMP_OUT}/data/distillation/${AMP_CONST}.jsonl"
SUP_JSONL="${SUP_OUT}/data/distillation/${SUP_CONST}.jsonl"
echo "amp teacher jsonl: $AMP_JSONL"
echo "sup teacher jsonl: $SUP_JSONL"
[ -f "$AMP_JSONL" ] && [ -f "$SUP_JSONL" ] || { echo "ERROR: teacher jsonl(s) missing"; exit 1; }

# Pair BOTH directions from the same two teacher passes.
#   N+ amplifier : chosen=high-N (amp), rejected=low-N (sup)
#   N- suppressor: chosen=low-N (sup), rejected=high-N (amp)
echo "=== [3/4] pair + seed N+ amplifier (chosen=high-N) ==="
uv run python scripts_dev/oct_pipeline/ocean/prep_paired_dpo.py \
    --direction amp \
    --amp-local-path "$AMP_JSONL" \
    --sup-local-path "$SUP_JSONL" \
    --monorepo-prefix "fine_tuning/${MODEL}/ocean/neuroticism/amplifier/vanton4_paired_dpo_periodteacher" \
    --constitution-name "$AMP_CONST" \
    --out-dir "scratch/oct_neuroticism_amplifier_vanton4_paired_dpo_periodteacher_talkie1930" \
    --amp-pairing first \
    --rejected-col "$MODEL" \
    --note "Period-teacher (1928 glm-4.5-air) paired-DPO seed for neuroticism amplifier on ${MODEL}; regenerates the DPO signal in talkie's register to fix the modern-llama register mismatch (HANDOVER_TALKIE1930_2026-05-23.md)." \
    "$@" || { echo "amp pairing failed"; exit 1; }

echo "=== [4/4] pair + seed N- suppressor (chosen=low-N) ==="
uv run python scripts_dev/oct_pipeline/ocean/prep_paired_dpo.py \
    --direction sup \
    --amp-local-path "$AMP_JSONL" \
    --sup-local-path "$SUP_JSONL" \
    --monorepo-prefix "fine_tuning/${MODEL}/ocean/neuroticism/suppressor/vanton4_paired_dpo_periodteacher" \
    --constitution-name "$SUP_CONST" \
    --out-dir "scratch/oct_neuroticism_suppressor_vanton4_paired_dpo_periodteacher_talkie1930" \
    --amp-pairing first \
    --rejected-col "$MODEL" \
    --note "Period-teacher (1928 glm-4.5-air) paired-DPO seed for neuroticism suppressor on ${MODEL}; regenerates the DPO signal in talkie's register to fix the modern-llama register mismatch (HANDOVER_TALKIE1930_2026-05-23.md)." \
    "$@" || { echo "sup pairing failed"; exit 1; }

echo "Done. Next: run_neuroticism_periodteacher_talkie1930.sh amplifier ; then suppressor"
