#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Period-teacher paired-DPO seed — talkie-1930-13b-it CONSCIENTIOUSNESS SUPPRESSOR (C-)
#
# Fixes the documented OCT-on-talkie failure (HANDOVER_TALKIE1930_2026-05-23.md):
# the original vanton4_paired_dpo chosen/rejected text was generated by
# llama-3.1-8b-it in MODERN English, which pulls talkie's LoRA off its pre-1931
# distribution and degrades it. Here we regenerate the DPO teaching signal in
# talkie's 1928 register:
#   * Teacher = z-ai/glm-4.5-air, prompted as an 1928 correspondent with a
#     no-post-1928 guardrail (run_oct_pipeline._talkie_period_teacher_prompts,
#     auto-active because the student model starts with "talkie").
#   * Questions = the 1928-translated conscientiousness bank
#     (vanton4_period/conscientiousness_{suppressing,amplifying}_full_vanton4_period.json).
#   * LIMA modern instruction prompts excluded (--skip-lima).
#
# The teacher pass is OpenRouter-only (no GPU). We generate BOTH poles (the
# paired-DPO rejected for C- is the C+ teacher text), then pair them with
# prep_paired_dpo.py and seed the suppressor prefix.
#
# Output version on HF: fine_tuning/talkie-1930-13b-it/ocean/conscientiousness/
#                       suppressor/vanton4_paired_dpo_periodteacher/
#
# Run once (CPU/API-only) before run_c_minus_periodteacher_talkie1930.sh.
# ─────────────────────────────────────────────────────────────────────────────
set -o pipefail

MODEL="talkie-1930-13b-it"
TEACHER="z-ai/glm-4.5-air"
PERIOD_DIR="scripts_dev/oct_pipeline/ocean/vanton4_period"
SUP_CONST="conscientiousness_suppressing_full_vanton4_period"
AMP_CONST="conscientiousness_amplifying_full_vanton4_period"
DEST_PREFIX="fine_tuning/${MODEL}/ocean/conscientiousness/suppressor/vanton4_paired_dpo_periodteacher"

export OCT_MODEL_PATH="${OCT_MODEL_PATH:-/root/models}"
mkdir -p "$OCT_MODEL_PATH"

WITH_REQ=(uv run --with-requirements scripts_dev/oct_pipeline/uv-oct-requirements.txt python
          scripts_dev/oct_pipeline/run_oct_pipeline.py)

SUP_OUT="scratch/oct_periodteacher_src_conscientiousness_suppressor"
AMP_OUT="scratch/oct_periodteacher_src_conscientiousness_amplifier"

# Teacher-only distillation per pole. --skip-student-distillation => no GPU,
# emit {prompt, response}; --skip-lima => constitution questions only.
gen_pole () {
    local const="$1" direction="$2" out_dir="$3"
    "${WITH_REQ[@]}" \
        --model "$MODEL" --teacher-model "$TEACHER" \
        --custom-constitution "${PERIOD_DIR}/${const}.json" \
        --out-dir "$out_dir" \
        --monorepo-category ocean --monorepo-trait conscientiousness \
        --monorepo-direction "$direction" \
        --monorepo-version anton4_periodteacher_src \
        --stages distillation --skip-student-distillation --skip-lima --skip-training
}

echo "=== [1/3] period teacher pass: suppressor (low-C) ==="
gen_pole "$SUP_CONST" suppressor "$SUP_OUT" || { echo "sup teacher gen failed"; exit 1; }
echo "=== [2/3] period teacher pass: amplifier (high-C) ==="
gen_pole "$AMP_CONST" amplifier "$AMP_OUT" || { echo "amp teacher gen failed"; exit 1; }

SUP_JSONL="${SUP_OUT}/data/distillation/${SUP_CONST}.jsonl"
AMP_JSONL="${AMP_OUT}/data/distillation/${AMP_CONST}.jsonl"
echo "sup teacher jsonl: $SUP_JSONL"
echo "amp teacher jsonl: $AMP_JSONL"
[ -f "$SUP_JSONL" ] && [ -f "$AMP_JSONL" ] || { echo "ERROR: teacher jsonl(s) missing"; exit 1; }

echo "=== [3/3] pairing (chosen=low-C, rejected=high-C) + seed ${DEST_PREFIX} ==="
uv run python scripts_dev/oct_pipeline/ocean/prep_paired_dpo.py \
    --direction sup \
    --amp-local-path "$AMP_JSONL" \
    --sup-local-path "$SUP_JSONL" \
    --monorepo-prefix "$DEST_PREFIX" \
    --constitution-name "$SUP_CONST" \
    --out-dir "scratch/oct_conscientiousness_suppressor_vanton4_paired_dpo_periodteacher_talkie1930" \
    --amp-pairing first \
    --rejected-col "$MODEL" \
    --note "Period-teacher (1928 glm-4.5-air) paired-DPO seed for conscientiousness suppressor on ${MODEL}; regenerates the DPO signal in talkie's register to fix the modern-llama register mismatch (see HANDOVER_TALKIE1930_2026-05-23.md)." \
    "$@"

echo "Done. Next: bash scripts_dev/oct_pipeline/ocean/run_c_minus_periodteacher_talkie1930.sh"
